### PR TITLE
Pi: removing redundant firmware installs

### PR DESCRIPTION
**Pull request by macmpi**
no longer needed since addition of firmware-brcm80211 package on Mar 14, 2016 as per https://github.com/volumio/Build/commit/4ad9736e8ec06422fd61813fb200925e91f907ff#diff-e745f2542baf16ec9199d5c899b4900c

```
apt-file list firmware-brcm80211
firmware-brcm80211: /lib/firmware/brcm/bcm43xx-0.fw
firmware-brcm80211: /lib/firmware/brcm/bcm43xx_hdr-0.fw
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43143-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43143.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43241b0-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43241b4-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4329-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4330-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4334-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4335-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43362-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43430-sdio.bin
firmware-brcm80211: /lib/firmware/brcm/brcmfmac43430-sdio.txt
firmware-brcm80211: /lib/firmware/brcm/brcmfmac4354-sdio.bin
firmware-brcm80211: /usr/share/bug/firmware-brcm80211/presubj
firmware-brcm80211: /usr/share/doc/firmware-brcm80211/changelog.gz
firmware-brcm80211: /usr/share/doc/firmware-brcm80211/copyright
```

### CODE REVIEW

**Comment by volumio** [comment]
Reverted, because wlan0 is not recognized after applying this. I am sorry, but won't accept any more PRs from you unless you give proof of testing in the PR message.

**Comment by macmpi** [comment]
There something weird at play here: arm (multiverse) build recipe and live re-install does not give the same result.
Removing every bcm firmware 
```
sudo apt-get remove firmware-brcm80211
rm -rf /lib/firmware/brcm
```
and re-installing clean with
`sudo apt-get install firmware-brcm80211`
does provide the expected full list of files
```
volumio@volumio:/lib/firmware/brcm$ ls -la
total 4268
drwxr-xr-x  2 root    root      4096 Jun 28 12:19 .
drwxrwxr-x 25 volumio volumio   4096 Jun 28 12:19 ..
-rw-r--r--  1 root    root     96224 Jun  7  2016 bcm43xx-0.fw
-rw-r--r--  1 root    root       180 Jun  7  2016 bcm43xx_hdr-0.fw
-rw-r--r--  1 root    root    385067 Jun  7  2016 brcmfmac43143-sdio.bin
-rw-r--r--  1 root    root    397312 Jun  7  2016 brcmfmac43143.bin
-rw-r--r--  1 root    root    455745 Jun  7  2016 brcmfmac43241b0-sdio.bin
-rw-r--r--  1 root    root    403855 Jun  7  2016 brcmfmac43241b4-sdio.bin
-rw-r--r--  1 root    root    253748 Jun  7  2016 brcmfmac4329-sdio.bin
-rw-r--r--  1 root    root    222126 Jun  7  2016 brcmfmac4330-sdio.bin
-rw-r--r--  1 root    root    451566 Jun  7  2016 brcmfmac4334-sdio.bin
-rw-r--r--  1 root    root    569291 Jun  7  2016 brcmfmac4335-sdio.bin
-rw-r--r--  1 root    root    219557 Jun  7  2016 brcmfmac43362-sdio.bin
-rw-r--r--  1 root    root    369576 Jun  7  2016 brcmfmac43430-sdio.bin
-rw-r--r--  1 root    root      1108 Jun  7  2016 brcmfmac43430-sdio.txt
-rw-r--r--  1 root    root    507752 Jun  7  2016 brcmfmac4354-sdio.bin
```
whereas recipe only installs the few following files from same package...
```
  96224 Jun 16  2014 bcm43xx-0.fw
  180 Jun 16  2014 bcm43xx_hdr-0.fw
  385067 Jun 16  2014 brcmfmac43143-sdio.bin
  455745 Jun 16  2014 brcmfmac43241b0-sdio.bin
  403855 Jun 16  2014 brcmfmac43241b4-sdio.bin
  253748 Jun 16  2014 brcmfmac4329-sdio.bin
  222126 Jun 16  2014 brcmfmac4330-sdio.bin
  451566 Jun 16  2014 brcmfmac4334-sdio.bin
  569291 Jun 16  2014 brcmfmac4335-sdio.bin
  219557 Jun 16  2014 brcmfmac43362-sdio.bin
  507752 Jun 16  2014 brcmfmac4354-sdio.bin
```
Multiverse issue in build setup or package install script bug?

**Comment by volumio** [comment]
It's due to the fact that probably the firmware are in raspberry's repo, not raspbians. Therefore we should install them in raspberryconfig.sh

**Comment by macmpi** [comment]
fixed with #213

**Pull request merged**
