### PR TITLE
Create subdirectories of /var/log

### PR DESCRIPTION
**Pull request by xipmix**
Issue #93 reported that /var/log was being created as a tmpfs on top of the SD card and that it lacked some subdirectories that the build system had placed there, e.g. /var/log/samba.
This series of changes ensures that the subdirs created during image build are reproduced on the tmpfs version of /var/log, once that filesystem is mounted at runtime.

This has been tested but as pieces, rather than making a full image and booting from it. Some independent build tests seem advisable.

Merging this will require moving /var/log/volumio.log to /var/log/volumio/volumio.log.

### CODE REVIEW

**Comment by gkkpch** [comment]
HI,

@xipmix can you verify the following:
I started on pine64 with its own set of image and config file and would like to stay compatible with the rest. 
I only need to replace 
      tmpfs   /var/log                tmpfs   size=20M,nodev,uid=1000,mode=0777,gid=4, 0 0
with
      tmpfs   /var/log                tmpfs   size=20M,nodev 0 0
in fstab, correct?

I on my side need to look at the x86 implementation.
There we have an fstab template dependency, which needs to be checked.

**Comment by xipmix** [comment]
On Tue, Nov 01, 2016 at 02:54:54PM -0700, Gé Koerkamp wrote:
> HI,
> 
> I only need to replace 
>       tmpfs   /var/log                tmpfs   size=20M,nodev,uid=1000,mode=0777,gid=4, 0 0
> with
>       tmpfs   /var/log                tmpfs   size=20M,nodev 0 0
> in fstab, correct?

Yes, I think that would be the only change to a pine64config.sh if
you are writing one.

> I on my side need to look at the x86 implementation.
> There we have an fstab template dependency, which needs to be checked.

Yes, I guess I forgot about that.

I also notice I missed some changes to scripts/configure.sh.

@volumio, please don't pull this yet.

> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/volumio/Build/pull/99#issuecomment-257710564

--

**Comment by xipmix** [comment]
I've now tested this more carefully - built a full rpi image and booted it - it works as expected, with the two addtional commits. Testing on x86 would still be a good idea.

**Comment by volumio** [comment]
I wll test it as well tomorrow! Great work so far!

**Comment by xipmix** [comment]
> I on my side need to look at the x86 implementation. There we have an fstab template dependency, which needs to be checked.

@gkkpch, I have looked into scripts/x86* and scripts/{volumio,}config.sh and the only fstab template dependency I can see is fixing up the uuid of the / partition. Am I missing something?

**Comment by gkkpch** [comment]
Yes, there us a bit in the initrd, i'll see to it tonight

----- Reply message -----

**Comment by gkkpch** [comment]
I believe it is OK

----- Reply message -----

**Comment by gkkpch** [comment]
Tested x86 just to make sure, works fine.
@xipmix: job well done!

**Comment by xipmix** [comment]
@volumio, I think this is ready now

**Comment by volumio** [comment]
Sorry for taking long.. Still testing it... I will merge it asap!

**Comment by xipmix** [comment]
> Sorry for taking long.. Still testing it... I will merge it asap! 

no worries, it's one you will want to be right.

**Comment by macmpi** [comment]
will this fix this issue too? https://github.com/volumio/Volumio2/issues/960

**Comment by macmpi** [comment]
Would be great to have it in.
One question though: with all logs mapped to RAM, how can we check/review events happening during shutdown/restart, as they will be gone after reboot?
Maybe we can add a setting in` /dev` page to store shutdown journalctl somewhere in flash for debug? Or any better idea?

**Comment by volumio** [comment]
Adding a setting to dev page to dump logs is a great idea. I'll do that

**Comment by xipmix** [comment]
@volumio I tried to fix the conflicts that have grown up over the last 3 months but now all of the changes I want to go in are being treated as conflicts. What should I do to fix this - make a new PR?

**Comment by macmpi** [comment]
@volumio actually my point was somehow different, sorry for being unclear: not dumping but keeping journal across reboot in particular, so that one can check/monitor journal across reboots (in particular the shutdown part).
`/dev` setting could flip between current default [`/etc/systemd/journald.conf`](https://wiki.archlinux.org/index.php/Systemd#Journal) setting, or modify with `Storage=persistent` and apply `systemctl restart systemd-journald`.

@xipmix you may have to resync your branch from master, and submit again I'm afraid...

**Comment by xipmix** [comment]
This PR is defunct, see #136 instead

**Pull request closed without merging**
