### PR TITLE
armbian image support in volumio build

### PR DESCRIPTION
**Pull request by chrismade**
in addition to native images in Volumio Build users have now a fallback option to create images based on armbian (so far tested for A20 based boards, may also work for others)

### CODE REVIEW

**Comment by volumio** [comment]
That's very welcome! But I think you forgot to add the file scripts/armbianimage.sh

**Comment by chrismade** [comment]
oh, that's true ... all files are missing:
scripts/armbianimage.sh
scripts/armbianconfig.sh
scripts/upgrade_armbian.sh
scripts/initramfs/init_armbian

will check tonite and fix asap

**Comment by chrismade** [comment]
I added the missing files - sorry for that mistake - and will now start a new pull request

**Comment by volumio** [comment]
Great!

**Comment by chrismade** [comment]
try reopen instead of creaing a new pull req

**Pull request merged**
