### PR TITLE
Introducing UEFI and Legacy Boot (hybrid image)

### PR DESCRIPTION
**Pull request by gkkpch**
I have not included a 32bit uefi bootloader as I am not able to test 32bit uefi firmware. 
All the notebooks/ PC's I have access to, have 64bit firmware.
I'll leave it until there is a real demand for it.

initrd needs more attention, on my asus notebook with 2 internal hhd's it throws an error while checking for factory-reset on usb or while checking for reset user-data. Not sure, which one, still need to debug that.

### CODE REVIEW

**Comment by volumio** [comment]
Great work gè!

**Comment by gkkpch** [comment]
I was just reading up on 32bit uefi firmware. It seems the cheaper Intel Atom based laptops have those, so the 32bit bootloader may be needed after all...

**Comment by balbuze** [comment]
hi Gé. I own a ld atom laptop... a medion akoya e1210 . I could do some test if you want/need

**Comment by gkkpch** [comment]
Yes, that would be perfect, can you build an x86 image? Or do I need to "send" you one?

**Comment by volumio** [comment]
I'll build one now... Master branch right?

**Comment by gkkpch** [comment]
yes

**Comment by balbuze** [comment]
I build several times RPI image. I think it is not really different . Just
give me the command line you use.

**Comment by gkkpch** [comment]
you need to install different prerequisites, just look an the build repo.
to build get the latest repo from master then enter:
`sudo ./build.sh -b x86 -d x86 -v <whateveryoufancy>`

**Comment by gkkpch** [comment]
or I send you a compressed image via "wetransfer", I woul dneed your email address via forum PM

**Comment by gkkpch** [comment]
let's continue on gitter...

**Comment by volumio** [comment]
Here is the image 
http://updates.volumio.org/x86/volumio/0.885/volumio-0.885-2016-05-29-x86.img.zip

**Comment by balbuze** [comment]
OK thanks. I keep you in touch. Not sure to test tonight..

**Pull request merged**
