### PR TITLE
HiFi 2 support for C1, change mount data part in initrd

### PR DESCRIPTION
**Pull request by gkkpch**

### CODE REVIEW

**Comment by gkkpch** [comment]
odroidcconfig can be removed!

**Comment by volumio** [comment]
Gè we got conflicts... Could you solve them?

**Comment by gkkpch** [comment]
just delete odroicconfig.sh, we don't need that. I don't get why it is complaing, in my repo it is not there

On 27 Sep 2016, at 23:16, Volumio <notifications@github.com> wrote:

Gè we got conflicts... Could you solve them?

**Comment by volumio** [comment]
Done

**Comment by gkkpch** [comment]
it could be related to the change in fstab. I you can delete the file, than that is fine. I split odroidcconfig in c1 and c2 configs

**Pull request merged**
