### PR TITLE
Pi: update brcm firmware & improve BT coexistence

### PR DESCRIPTION
**Pull request by macmpi**
https://github.com/RPi-Distro/firmware-nonfree/issues/8#issuecomment-615339218
(need to get file from https://archive.raspberrypi.org/debian/pool/main/f/firmware-nonfree/firmware-brcm80211_20190114-1+rpt6_all.deb )

### CODE REVIEW

**Comment by volumio** [comment]
Were you able to test it with your PI?

**Comment by macmpi** [comment]
No, unfortunately as I do not have a Pi4, just PiZeroW.
Reports in original thread seem rather positive.
Firmware files were quite behind anyway (+rpt2), in particular without kr00k patches

**Comment by volumio** [comment]
in your PIZerow works?

**Comment by macmpi** [comment]
Note latest NVRAM param tweak is on brcmfmac43455, not brcmfmac43430 of PiZeroW

My PiZeroW doing Wifi & BT is on a Alpine build (mpd audio out via bluez-alsa), not Volumio, but works good with those firmware files.

**Pull request merged**
