### PR TITLE
Add Aoide-DACs support.

### PR DESCRIPTION
**Pull request by howardqiao**
Add Aoide-DACs support.

### CODE REVIEW

**Comment by volumio** [comment]
Hi, thanks for the PR!
Before integrating we need to make sure that they are GPL and we're GPL compiant:

Please confirm that:

The code submitted is released under GPL (indicate the version)
Please show where sources for the binaries can be found
You will take all responsabilities and obligations concerned by the distribution of the binaries you provided. This includes making the sources available to everyone requiring them.
You agree to free Volumio and INTUITU di Michelangelo Guarise from any responsability deriving from distribution of the binaries you provided, and to provide eventual indemnifycation for damages

Reply "I agree", along with your name to agree

**Comment by volumio** [comment]
Sorry, not merging a change of repository

**Comment by gkkpch** [comment]
Why are we changing the kernel and removing all Allo DAC modules?

**Comment by macmpi** [comment]
Yes very confusing indeed.
@howardqiao are your trying to include the same thing as here https://github.com/raspberrypi/linux/pull/1559#issuecomment-232751431 ?

**Comment by volumio** [comment]
@howardqiao There's no way I will merge this. To get your DAC up and running, please just provide a zip file for the 2 kernels you see in raspberryconfig.sh (better if via email) and agree to the terms in the second message. So I am closing this one, please open another PR doing what I've asked, since its the only way we can accept your work. Thanks

**Pull request closed without merging**
