### PR TITLE
Exit early if an unsupported device is passed in

### PR DESCRIPTION
**Pull request by ashthespy**
This should cover things as described by @xipmix -- or did I miss something? 
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b armv8 -d raspbberypi5
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <raspbberypi5> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -d raspbberypi5
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <raspbberypi5> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b raspbberypi5
[ .... ] Running Volumio Image Builder -  
[ warn ] No device flag passed to builder, building only  
[ .. ] Checking whether we are running as root 
[ .. ] Creating log directory 
[ .. ] Setting default Volumio variant 
[ .... ] Creating raspbberypi5 rootfs  
[ .. ] Defaulting to release [ Buster ]
[ warn ] No base system configuration file found [ raspbberypi5.conf ]
```
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b raspbberypi5 -d armv8
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <armv8> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b armv8
[ .... ] Running Volumio Image Builder -  
[ warn ] No device flag passed to builder, building only  
[ .. ] Checking whether we are running as root 
[ .. ] Creating log directory 
[ .. ] Setting default Volumio variant 
[ .... ] Creating armv8 rootfs  
[ .. ] Defaulting to release [ Buster ]
[ .. ] armv8 rootfs exists, cleaning it 
[ .... ] Setting up Multistrap environment  
[ .. ] Preparing rootfs apt-config 
[ .. ] Adding SecureApt keys to rootfs 
Executing: /tmp/apt-key-gpghome.48mm2JyMLt/gpg.1.sh --fetch-keys https://deb.nodesource.com/gpgkey/nodesource.gpg.key
gpg: requesting key from 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
gpg: key 1655A0AB68576280: public key "NodeSource <gpg@nodesource.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Executing: /tmp/apt-key-gpghome.T5669FZxtc/gpg.1.sh --fetch-keys https://ftp-master.debian.org/keys/archive-key-10.asc
gpg: requesting key from 'https://ftp-master.debian.org/keys/archive-key-10.asc'
^C
gpg: signal Interrupt caught ... exiting
[ error ] Build script failed!! 
```
And this beauty that I actually ran :-D
```bash
/.../VolumioOS [master ↑1 +21 ~1 -0]$ ./build_docker.sh -b x64 -d x86_arm64 -v 0.00
[ .... ] Running Volumio Image Builder -  
[ error ] No configuration found for <x86_arm64> 
[ .. ] Build system currently supports 12 devices: [ mp1 nanopineo2 odroidc1 odroidc2 odroidc4 odroidn2 orangepilite raspberry rockpis tinkerboard x86_amd64 x86_i386 ]
```

### CODE REVIEW

**Comment by volumio** [comment]
@xipmix please confirm if this achieves what you would like to do, so we merge it

**Comment by xipmix** [comment]
I went down a similar road with a separate function but didn't include the BUILD check, because I guess I thought that specifying a bad device was handled already...  I'm a bit surprised the ```-n $DEVICE``` check (and ```-n $BUILD```) works with the variable unset, I would have written ```-n "$DEVICE"```. But clearly it does work, so from my perspective, merge away.

**Comment by ashthespy** [comment]
Good point, will quote it just to be consistent..

**Comment by ashthespy** [comment]
Added the quotes for good measure and to be consistent.. RTM from my side!

**Pull request merged**
