### PR TITLE
Blacklisting unwanted USB wifi drivers

### PR DESCRIPTION
**Pull request by macmpi**
rtl8192cu and rtl8xxxu come with 4.19.x kernel

### CODE REVIEW

**Comment by volumio** [comment]
Thanks, can we add a version check before those? 
I mean: if kernel version is >= 4.19 then blacklist them 

What do you think?

**Comment by macmpi** [comment]
Hi.
Your call: don't know how much you intend to support/roll-back to older kernels: anyway these would not cause issue with earlier kernels either...
(BTW about older kernels: could we not remove the older ones and linked stuff?)

**Comment by volumio** [comment]
We need older kernel switches for some OEM builds ;) 
To this regard that's why I asked for the switch as well ;)

**Comment by macmpi** [comment]
Comparing version numbers is a bit tricky... (and those blacklists cause no harm to previous Kernels)

Would [this switch](https://stackoverflow.com/questions/16989598/bash-comparing-version-numbers) make sense to you? (second one, without sort -V)?

**Comment by macmpi** [comment]
:)  forgot I did submit that a while back.
We inherit those blacklists from `raspberrypi-sys-mods` anyway, so closing.

Note though, `rtl8192cu` seems better for AP mode under 4.19...and may come back depending on https://github.com/RPi-Distro/raspberrypi-sys-mods/issues/37

**Pull request closed without merging**
