### PR TITLE
Pi: Add TauDAC-DM101 Firmware

### PR DESCRIPTION
**Pull request by taudac**

### CODE REVIEW

**Comment by macmpi** [comment]
mind current kernel in master is 4.9.41 not 4.9.36!

**Comment by macmpi** [comment]
Overlay addition looks fine, but kernel version (and related archive file name, folder names within archive, and maybe binaries) look still incorrect.

As kernel is updated from time to time, it's desirable to use related KERNEL_VERSION variable in archive naming, and regularly make updated drivers available: any chance they will be pushed to kernel releases?

**Comment by taudac** [comment]
How about [rpi-volumio-4.9.41-taudac-modules](https://github.com/taudac/modules/tree/rpi-volumio-4.9.41-taudac-modules)? I was trying to follow [this proach](http://repo.volumio.org/Volumio2/Firmwares/rpi-volumio-4.4.9-pisound-modules.tgz).

**Comment by taudac** [comment]
@macmpi Is a pre-release Volumio image containing kernel 4.9.41 available? I would like to test the TauDAC drivers.

**Comment by macmpi** [comment]
I think @volumio has built one available [here](https://volumio.org/forum/help-needed-test-the-new-updater-t7057-80.html#p38017) for tests; alternatively you may build your own following instructions on this repo.

**Comment by taudac** [comment]
@macmpi @volumio PR [#261](https://github.com/volumio/Build/pull/261) contains modules for 4.9.41, closing this PR.

**Pull request closed without merging**
