### PR TITLE
4.14.70 commit fix for kernel panics

### PR DESCRIPTION
**Pull request by macmpi**
as per https://github.com/volumio/Build/commit/c00a19098320053824010d132d6bfb39774a7d2f#commitcomment-30554050

### CODE REVIEW

**Comment by volumio** [comment]
Is it safe to merge? Even if it's not tied to a version bump? Will we have troubles with headers and uname string?

**Comment by macmpi** [comment]
I do not expect any issue, but can not test right now.
rpi-update just needs a commit number: we did similar things in the past.
Kernel rev is unchanged (still 1144)

**Comment by macmpi** [comment]
If you do not feel confortable, just jump to 4.14.71 in a few bit: it potentially contains a major USB fix (awaiting final confirmation) ;)
https://github.com/Hexxeh/rpi-firmware/commit/c919d632ddc2a88bcb87b7d0cddd61446d1a36bf

**Comment by volumio** [comment]
Done https://github.com/volumio/Build/commit/19491f50eded236de6874d31640dedebc248dfa0

**Pull request closed without merging**
