### PR TITLE
SKIP_CHECK_PARTITION now merged

### PR DESCRIPTION
**Pull request by macmpi**
BTW how about installing `rpi-update` the `apt` way?

### CODE REVIEW

**Comment by ashthespy** [comment]
General question (also to @macmpi as you seem to know the tricks of the Rpi's ;-) )
Is there a reason not to use the [`ROOT_PART`/`BOOT_PART`](https://github.com/Hexxeh/rpi-update#root_path-and-boot_path) to copy files into the rootfs, instead of running the script from chroot?

**Comment by ashthespy** [comment]
Is this still valid or can it be closed?

**Comment by macmpi** [comment]
Have not tested lately
It seems @volumio ´s cached version still differs from original hexxeh repo.
Would probably be worth syncing (more future proof), since hexxeh adapted WANT_PI4 SKIP_CHECK_PARTITION a while ago.

Also using apt package rather then curl to pull it would probably be cleaner too

**Comment by ashthespy** [comment]
Closing this as I don't think we are going to be doing anything radical with the master (Jessie) branch going forward. 
[volumioOS branch](https://github.com/volumio/Build/blob/0804b7881fd390d7687d5e6424ed71036810f130/recipes/devices/pi.sh#L179) uses the upstream `rpi-update` already.

**Pull request closed without merging**
