### PR TITLE
Removing superfluous apt-get update

### PR DESCRIPTION
**Pull request by macmpi**
same as https://github.com/volumio/Build/pull/216 for other devices as requested.

### CODE REVIEW

**Comment by volumio** [comment]
Sorry, this is necessary because we do clean the apt cache sometimes in the patches

**Comment by macmpi** [comment]
then you may want to also revert the Pi one accordingly #216

**Comment by macmpi** [comment]
@volumio (this is old stuff, but just to make sure):
Since this PR has been cancelled and for consistency, don't you want to revert https://github.com/volumio/Build/pull/216 which originally accomplished same on Pi?

**Comment by volumio** [comment]
I am checking now... thanks

**Pull request closed without merging**
