### PR TITLE
Fixed moving GTP partition backup tabled (initrd)

### PR DESCRIPTION
**Pull request by gkkpch**
You may want to wait with this as solaar74 reported problems on reboot after a successful first start.
Not sure yet if this is boot-related, it fails on mounting devices AFTER initrd

### CODE REVIEW

**Comment by volumio** [comment]
Gé, is this safe to merge?

**Comment by gkkpch** [comment]
no, not yet. I'm still waiting for final feedback after additional changes. solaar74, FYC and balbuze are going to test...

**Comment by volumio** [comment]
Let me know when you're done with that... Also, what if we prepare the installer in the meanwhile?

**Comment by gkkpch** [comment]
What did you have in mind for the installer?
I could try the following: a whiptail based menu script to select the hard drive volumio should be copied to, then after issueing a warning, use 'dd' to copy. I somehow need to get this menu to run first (rc.local), but only after selecting a corresponding boot entry. After succesfull installation, the boot menu on the hard drive would be set to "automatic" (immediate boot). 
You might have a better idea though...

**Comment by volumio** [comment]
This is a good idea! But we can also offer it in the UI, under system. By having this script done in bash and reporting progress on stdout we can use it both ways. What do you think?

**Comment by gkkpch** [comment]
I would prefer the UI, makes it more user friendly. With a proper warning, that he/she is overwriting the selected disk without being recoverable. Probably have to put a note in it too, that a backup might be advisable.

Also think we should immediate boot, having menus does not add anything at all, unless you want to use it to trigger the install programm (initramfs could create a flag file depening on boot grub/ syslinux boot parameters)


On 23.08.2016, at 16:20, Volumio <notifications@github.com> wrote:

This is a good idea! But we can also offer it in the UI, under system. By having this script done in bash and reporting progress on stdout we can use it both ways. What do you think?

**Comment by volumio** [comment]
I can do it in the UI without any problem... But may I rely on you for the script? Agree also that the menu adds nothing other than waiting time... 
You know what would be fantastic? An animated loading screen ...

**Comment by gkkpch** [comment]
Good news from balbuze, my debug initrd gets past the "dead" point on his medion notebook. I think the issue has been resolved, when confirmed, i'll clean up for a PR.

On 23.08.2016, at 17:41, Volumio <notifications@github.com> wrote:

I can do it in the UI without any problem... But may I rely on you for the script? Agree also that the menu adds nothing other than waiting time... 
You know what would be fantastic? An animated loading screen ...

**Comment by gkkpch** [comment]
ok, then i need to know what the script(s) should look like.
probably use lsblk to list the disks (and remove the boot disk from the list).
lsblk returns well readable device data in a script-friendly format.
Then we need dd in a way that it spits out copy progress, don't know the parameter by head. Have you got an example script somewhere from the spotify install I can have a look at?



On 23.08.2016, at 17:41, Volumio <notifications@github.com> wrote:

I can do it in the UI without any problem... But may I rely on you for the script? Agree also that the menu adds nothing other than waiting time... 
You know what would be fantastic? An animated loading screen ...

**Comment by volumio** [comment]
I think we could call it the clone\install function, and it may be well done for all devices. With this you can clone a volumio install (for backup purposes, why not...)  on a new drive.
It can be in phases, like a wizard: 
select the drive 
clone\install 
apply.

The difference beetween clone and install will be that with clone you'll just do a straight dd, with install you do a dd then delete user data and resize data part. 
What do you think?

**Comment by gkkpch** [comment]
Sounds ok, let's do this....

**Comment by gkkpch** [comment]
But remember, feature freeze :)

**Comment by volumio** [comment]
Lol, yes you're right... Let's fix stuff and then implement it.... Let's see in a "parallel" way

**Comment by gkkpch** [comment]
ok, can you merge this one? Removing the bootmenu for grub/uefi will be done with the next fix, for syslinux it was never there I noticed.

**Comment by volumio** [comment]
Gè, guess we have a regression here... Cannot boot it anymore on any of my devices... Is there any additional dependency of the boot script? I'll try rebuilding it...

**Comment by volumio** [comment]
Nope... seem not to work... If you want to try it:
http://updates.volumio.org/x86/volumio/0.986/volumio-0.986-2016-08-26-x86.img.zip

**Comment by gkkpch** [comment]
There are new dependencies,  gdisk was added to the recipes for using it in init-86.
==>> libstdc++.so.6 was added too, perhaps you need that one on the host??

**Comment by gkkpch** [comment]
it is in recipes, so that can't be it.

**Comment by gkkpch** [comment]
checked my build from" volumio/Build". It boots legacy and uefi (but volumio.service is not starting)
flashed your build from above. It boots legacy and uefi, same issue with volumio.service.
works on my Gigabyte, HP Notebook, Asus Notebook but..... not on Intel NUC, bugger!!!!

**Comment by gkkpch** [comment]
is it possible to revert?

**Comment by gkkpch** [comment]
just wait, starting with a version from 15.07 to see where it went wrong

**Comment by gkkpch** [comment]
No need to revert!!!!!!!!
Nothing wrong with the build, the problem is another one :smile: :smile: :smile: :smile:
You're going to like this one, it is booting fine from the new image, but not the way we expected:
  - we both had a volumio install on the nuc's or notebook's hdd, right?
  - now, when we boot, how do we locate our disks devices? Get it??

**Comment by gkkpch** [comment]
changing by-label back to by-uuid and fixing fstab at boot time

**Pull request merged**
