### PR TITLE
get firmware & kernel from latest stable

### PR DESCRIPTION
**Pull request by macmpi**
Hopefully working: supposedly same as 2018-03-13 Raspbian
Note: MrEngman drivers may not be available yet, Taudac may need to be updated too..

### CODE REVIEW

**Comment by volumio** [comment]
You did it! It works! Great !

**Comment by macmpi** [comment]
Sweet!
Seems MrEngman is working on compiling his drivers.
Might be safer if @taudac could also recompile with that slightly updated kernel version...

**Comment by taudac** [comment]
Can't find the right kernel source, firmware commit 936a8dc3 points to kernel commit 921b6254. The later doesn't exist.

**Comment by macmpi** [comment]
Yes: it's a bit of a hack-ish version: see https://github.com/raspberrypi/firmware/issues/954
On the more standard release front, please note 4.14.29 is out.

**Comment by taudac** [comment]
I have recompiled the modules. They are binary identical to my original "for-4.9.80" release.

**Comment by macmpi** [comment]
Thanks for checking and confirmation.

While I understand upstreaming your driver might be a long process, would you be considering submitting directly to https://github.com/raspberrypi/linux as a first step?
It very much seems other DAC vendors did this, and got integrated pretty fast.

**Pull request merged**
