### PR TITLE
Use proper 4.4 branch for rpi-update

### PR DESCRIPTION
**Pull request by macmpi**
rpi-update (default) **master** branch is now on 4.9.y
Use **stable** branch while volumio sits on 4.4.y

### CODE REVIEW

**Comment by volumio** [comment]
No way, we can't change kernel now. Simply because people will need to reflash and can't use the updater. 
We're preparing a new updater that will update the kernel. Until we have it, we stay in this kernel.
Plus, we should ALWAYS use a kernel commit, since we need to keep it consistent across releases. Last thing, before releasing a kernel we need to do extensive testing to see if everything (i2s DACs mainly, works as expected)

**Comment by macmpi** [comment]
I think you missed the point I made.
It is NOT about changing the kernel indeed.
But it is a fact that rpi-update master is now on 4.9 (since a few weeks).
So if we want to avoid bizarre updates in the build process with firmware files coming from 4.9, then we are better explicitly pointing to the right branch now.

**Comment by volumio** [comment]
Sorry I misunderstood indeed. 
So, basically this will just stick the firmware to the stable branch, correct ?

**Comment by macmpi** [comment]
Yes.
This will by the way help supporting newer PiZero W.
Firmware got updated March 3rd, right after v2.114 build !...

**Comment by volumio** [comment]
Mmm guess its too late then, lol 
http://updates.volumio.org/pi/volumio/2.118/volumio-2.118-2017-03-07-pi.img.zip

**Comment by macmpi** [comment]
you may want to check firmware files, as they probably come from 4.9 branch!...

**Comment by volumio** [comment]
Yep, I will check them, and check this commit and eventually merge...

**Comment by macmpi** [comment]
Hopefully they are the same...
But pointing to proper branch is more future proof until you move to next kernel: actually it's a good lesson learn, let's make explicit reference to branches when possible, as master moves.

**Comment by macmpi** [comment]
Firmware files are definitely not the same between the 2 branches.
Made a build with the changes, and it has proper 4.4 firmware files.

Still, something strange, newer PiZero W .dtb does not come... (in either case BTW: not present in 2.118-2017-03-07-pi.img.zip either which [does not work on PiZero W](https://volumio.org/forum/with-new-rpi-zero-t6050.html#p29551).

**Comment by macmpi** [comment]
Actually firmware files from 4.4 (stable) and 4.9 (master) do not look the same...
Built an image with the proposed change, and files do come from 4.4 branch, but MD5 is different from stable ones: I'm quite puzzled.

Another weird thing, in my image, and the one you built, new PiZero W .dtb file is not present!...

**Comment by volumio** [comment]
OT: Could you help me on this one? I think you might have something up your sleeve! 
https://volumio.org/forum/installing-the-touch-display-plugin-t6032.html#p29602

**Comment by macmpi** [comment]
hum... 2.114 probably had the 4.9 firmware mix already. Let me check if the plugin installs fine on my recent build...(PS, can't find how to view the build log)

**Comment by macmpi** [comment]
@volumio did you have a chance to check this?
I'm running my own Build image with it for few days, and it looks fine: it has consistent 4.4 files.

I don't think we want to keep a mixed bag of 4.4 and 4.9 files in the build in upcoming release images as it is today with 2.118 (and maybe 2.114): this may produce quite unexpected outcomes at some point.

**Pull request merged**
