### PR TITLE
protect /dev/shm

### PR DESCRIPTION
**Pull request by macmpi**
just a good practice
https://www.cyberciti.biz/faq/linux-add-nodev-nosuid-noexec-options-to-temporary-storage-partitions/

### CODE REVIEW

**Comment by macmpi** [comment]
Running my Pi for few days already with this fstab change, and all is great.
Maybe I should propagate this to other platform scripts too, so that the PR is consistent across the board?

**Comment by volumio** [comment]
Yes please extend it to other platforms...

**Comment by macmpi** [comment]
Done. Amazing number of supported platforms indeed :)
only x86 missing, but I guess it's somewhere else

**Comment by gkkpch** [comment]
Yes, x86 works with a template file, I'll fix it later tonight

On 14 Mar 2017, at 15:46, macmpi <notifications@github.com> wrote:

Done. Amazing number of supported platforms indeed :)
only x86 missing, but I guess it's somewhere else

**Comment by gkkpch** [comment]
The x86 version is not using shared memory, I also doubt it would have any noticable advantage in this case.

**Comment by volumio** [comment]
Gé, do you think it might bring regressions for arm based platforms?

**Comment by gkkpch** [comment]
Difficult to judge as I don't know which volumio system parts are heavily using share memory to communicate.
Only regression testing can tell and that would need to be done for at least a few of them.

On 14 Mar 2017, at 21:01, Volumio <notifications@github.com> wrote:

Gé, do you think it might bring regressions for arm based platforms?

**Comment by volumio** [comment]
We usually do write some stuff in /tmp which is mounted on RAM, some files we write on /tmp need to be executable

**Comment by macmpi** [comment]
Yes and it is still the case with running the change: one can still execute things in `/tmp` (just confirmed again on my Pi)
Only `/dev/shm` is protected

**Comment by volumio** [comment]
Should be fine then. Merging

**Pull request merged**
