### PR TITLE
Support for OrangePi devices

### PR DESCRIPTION
**Pull request by pkendall64**
This initial cut supports the OrangePi Lite and One devices.

### CODE REVIEW

**Comment by VincentGijsen** [comment]
I've build this version, runs like a kitten, but for a single issue, i didn't notice when on a PI1, the DAC (i use a ess9203. With the snd_soc_pcm5102a, it runs but has issues with some files especially 24bit or >44.1khz, resulting in Alsa hw0.0 errors. 

On the pi i used the Hifiberry overlay which (tried) to play everything. Another thing I noticed is the slight noise on boot, after the intro-tune, its absolutly quite but didn't notice this behavior before. 

Building its with `./build.sh -b armv7 -d orangepione` whent great, awesome work.

On the good side, its a zillion times faster then my old pi-setup.

**Comment by ashthespy** [comment]
Just built it for the orangepilite - and am listening to some tunes with a PCM5012a dac. Can confirm what @VincentGijsen says - it purrs, especially coming from a pi0 ;-)

I had a small hiccup with the initial hotpot - it didn't let me connect to it, I am no expert - but I'm guessing this is an artefact of the included `8189fs` driver - there are some ([1](https://forum.armbian.com/topic/4411-hostapd-on-orange-pi-light-realtek-driver/),[2](https://forum.armbian.com/topic/1713-solved-opi-lite-wifi-cannot-connect-to-wpa/),[3](https://forum.armbian.com/topic/1775-wicd-gets-erroneous-bad-password/?tab=comments#comment-14708)) issues floating around about the driver and authentication issues.  
Once I disabled the auth in the via serial console, to initially reach the webUI, I've not faced any issues so far with the WiFi.
Maybe a good idea to enable the usbgadget on the Lite?

**Comment by pkendall64** [comment]
@VincentGijsen I want to try more DACs on the OrangePi, but I currently only have the PCM5102A. I'll order an ESS9203 one from AliExpress. If you have a link to a good one I'll get that to try.

@ashthespy Nice find on the the custom hostapd. I'll do a build of that and see if that fixes the problems and I'll integrate that into the build.

Thanks for the feedback.

**Comment by VincentGijsen** [comment]
@pkendall64 : I use this (dirt cheap) https://www.ebay.com/itm/DAC-Sabre-ES9023-Digital-analog-I2S-24bit-Decoder-Board-Mode-Conversion-D4J7/162646301263?hash=item25de799a4f:g:jscAAOSw4CFY2iWI can be bought anywhere. 

Would you happen to know how to get the I2C stuff going, I am stuggeling to get LCDproc going. The `i2cdectec -y 0` shows every run new and disappeared devices. So getting the feeling the dtb overlay either crippes the peripheral, or I have overlookt something (trivial). I would really like to have the cheap i2c port-expander based hd44780 modules going, due the wiring-simplicity.

**Comment by pkendall64** [comment]
If there are other things we need to add can we talk about them on the forum https://volumio.org/forum/volumio-orange-t7081.html. I don't think it's right to discuss them in the PR.

**Comment by pkendall64** [comment]
@VincentGijsen can you provide the changes to get i2c to work and I'll include that in the DTS/DTB so it works out-of-the-box for others.

**Comment by VincentGijsen** [comment]
@pkendall64 : yep figured so much, i just prepped a gist, but you've already solved it :)

**Comment by ashthespy** [comment]
@pkendall64 are you accepting pull requests? I'd like to merge in gpio access from non root user space.

**Comment by gkkpch** [comment]
@pkendall64 : could you check your PM at the Volumio site please.

**Comment by pkendall64** [comment]
@ashthespy I have accepted you PR, thank you.
@gkkpch I have read and responded to your PM, thanks.

**Pull request merged**
